//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSS_Board_Maintenance.Models
{
    using System;
    using System.Collections.Generic;

    public partial class employee_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee_user()
        {
            this.maintenance_rutine = new HashSet<maintenance_rutine>();
        }

        public int employee_id { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string last_name { get; set; }
        public byte[] signature { get; set; }
        public string role { get; set; }
        public Nullable<bool> verification { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maintenance_rutine> maintenance_rutine { get; set; }
        public string GetFullName()
        {
            return name + " " + last_name;
        }
    }
}
