//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSS_Board_Maintenance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenance_schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public maintenance_schedule()
        {
            this.maintenance_rutine = new HashSet<maintenance_rutine>();
        }
    
        public string ms_id { get; set; }
        public string type { get; set; }
        public string dependency { get; set; }
        public string building { get; set; }
        public string level { get; set; }
        public string location { get; set; }
        public string nomenclature { get; set; }
        public int month_scheduled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maintenance_rutine> maintenance_rutine { get; set; }
    }
}
