//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSS_Board_Maintenance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenance_rutine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public maintenance_rutine()
        {
            this.termography_files = new HashSet<termography_files>();
        }
    
        public int mr_id { get; set; }
        public string ms_id { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public int slots_quantity { get; set; }
        public int slots_available { get; set; }
        public string transf_capacity { get; set; }
        public string general_protection { get; set; }
        public string initial_termography { get; set; }
        public string general_cleaning { get; set; }
        public string cable_managment { get; set; }
        public string retighten { get; set; }
        public string rotulation { get; set; }
        public string final_termography { get; set; }
        public string cover_placement { get; set; }
        public string protection_capacity { get; set; }
        public decimal voltage_01 { get; set; }
        public decimal voltage_02 { get; set; }
        public decimal voltage_03 { get; set; }
        public decimal current_01 { get; set; }
        public decimal current_02 { get; set; }
        public decimal current_03 { get; set; }
        public decimal current_n { get; set; }
        public string observations { get; set; }
        public int employee_id { get; set; }
    
        public virtual employee_user employee_user { get; set; }
        public virtual maintenance_schedule maintenance_schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<termography_files> termography_files { get; set; }
    }
}
