//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSS_Board_Maintenance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BM_010_ISSSEntities : DbContext
    {
        public BM_010_ISSSEntities()
            : base("name=BM_010_ISSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dependency> dependencies { get; set; }
        public virtual DbSet<employee_user> employee_user { get; set; }
        public virtual DbSet<maintenance_rutine> maintenance_rutine { get; set; }
        public virtual DbSet<maintenance_schedule> maintenance_schedule { get; set; }
        public virtual DbSet<termography_files> termography_files { get; set; }
    }
}
