//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISSS_Board_Maintenance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class termography_files
    {
        public int tf_id { get; set; }
        public int mr_id { get; set; }
        public byte[] termography_file { get; set; }
        public string termography_file_name { get; set; }
        public string termography_file_extension { get; set; }
    
        public virtual maintenance_rutine maintenance_rutine { get; set; }
    }
}
